version: '3'
services:
  api:
    image: jeytogo/chat:latest
    build:
      context: .
      dockerfile: dockerfile
    # working_dir: /work
    container_name: avocado_chat
    # command: cargo run
    ports:
      - "8080:8080"

  # db:
  #   image: postgres:15.2-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=${DATABASE_NAME}
  #     - POSTGRES_USER=${DATABASE_USER}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #   ports:
  #     - "${DATABASE_PORT}:${DATABASE_PORT}"
  #   volumes:
  #     - ./migrations/20221203231817_setup.up.sql:/docker-entrypoint-initdb.d/setup.sql
