version: '3'
services:
  ai_server:
    build: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "8080:8080"
    tty: true
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080