# 本番環境用
# docker compsoe コマンドは標準でdockdr-compose.ymlを参照するので、
# 競合は気にしなくてOK
version: '3'
services:
  ai_server:
    image: rskymst/avocado-py:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - '8080:8080'
    tty: true
    working_dir: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
